version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    environment: 
      ENV: TEST
      api: '{"email_recipients":"foo@bar.com", "mailgun":"mockmailgunapitoken","grecaptcha":"mockgrecaptchaapitoken"}'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: sudo python -m pip install pytest
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
